
mhamed_cecilia:
    resource: "@MhamedCeciliaBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    pattern:   /test/login_check

logout:
    pattern:   /logout

add_user:
    pattern:   /adduser
    defaults:  { _controller: OCUserBundle:Security:adduser }
