mhamed_cecilia_homepage:
    path:     /homepage
    defaults: { _controller: MhamedCeciliaBundle:Main:home }


mhamed_cecilia_test:
    path:     /homepage/test
    defaults: { _controller: MhamedCeciliaBundle:Main:test }



mhamed_cecilia_quiz:
    path:     /homepage/quiz/{id}
    defaults: { _controller: MhamedCeciliaBundle:Main:showQuiz }
    requirements: 
        id: \d+




mhamed_cecilia_appointment:
    path:     /homepage/appointment
    defaults: { _controller: MhamedCeciliaBundle:Main:appointment }



mhamed_cecilia_advise_article:
    path:     /homepage/advise/{id}
    defaults: { _controller: MhamedCeciliaBundle:Main:showAdvise }
    requirements: 
        id: \d+


mhamed_cecilia_advises :
    path: /homepage/advise
    defaults: { _controller: MhamedCeciliaBundle:Main:advises }



mhamed_cecilia_QA:
    path:     /homepage/QA
    defaults: { _controller: MhamedCeciliaBundle:Main:QA }

