mhamed_cecilia_homepage:
    path:     /
    defaults: { _controller: MhamedCeciliaBundle:Main:home }


mhamed_cecilia_test:
    path:     /tests
    defaults: { _controller: MhamedCeciliaBundle:Main:test }



mhamed_cecilia_quiz:
    path:     /quiz/{id}
    defaults: { _controller: MhamedCeciliaBundle:Main:showQuiz }
    requirements: 
        id: \d+




mhamed_cecilia_appointment:
    path:     /appointment
    defaults: { _controller: MhamedCeciliaBundle:Main:appointment }



mhamed_cecilia_advise_article:
    path:     /advise/{id}
    defaults: { _controller: MhamedCeciliaBundle:Main:showAdvise }
    requirements: 
        id: \d+


mhamed_cecilia_advises :
    path: /advise
    defaults: { _controller: MhamedCeciliaBundle:Main:advises }



mhamed_cecilia_QA:
    path:     /QA
    defaults: { _controller: MhamedCeciliaBundle:Main:QA }


